import type { AutoResearchRunRecord } from './history';

export const AUTORESEARCH_DEMO_RUN_ID = 'demo-autoresearch-run';

export function isDemoRun(run: Pick<AutoResearchRunRecord, 'id'> | null | undefined): boolean {
  return run?.id === AUTORESEARCH_DEMO_RUN_ID;
}

export function createAutoResearchDemoRun(): AutoResearchRunRecord {
  return {
    id: AUTORESEARCH_DEMO_RUN_ID,
    title: 'Benchmark fixture optimization sweep',
    status: 'completed',
    createdAt: '2026-05-05T18:30:00.000Z',
    updatedAt: '2026-05-05T19:02:00.000Z',
    startedAt: '2026-05-05T18:31:00.000Z',
    endedAt: '2026-05-05T19:02:00.000Z',
    config: {
      experimentDir: './benchmarks/tiny-autoresearch-digits',
      workdir: './benchmarks/tiny-autoresearch-digits',
      sessionFilePath: './artifacts/autoresearch/demo/session.md',
      livingDocPath: './artifacts/autoresearch/demo/report.md',
      metric: 'cv_accuracy',
      direction: 'higher',
      iterations: 6,
      baseline: 0.963284,
      preferredPythonCommand: 'python3',
      repoStatus: 'clean',
      dirtyFileCount: 0,
      gpuTelemetryAvailable: true,
      gpuSummary: 'temp=49C, fan=37%, util=41%, memory=1811/8192MB',
      gpuTemperatureC: 49,
      gpuFanSpeedPercent: 37,
      gpuUtilizationPercent: 41,
      gpuMemoryUsedMb: 1811,
      gpuMemoryTotalMb: 8192,
      configSnapshot: {
        configId: 'demo-config',
        configName: 'Demo config',
        provider: 'demo',
        providerLabel: 'Demo Provider',
        apiFormat: 'responses',
        baseUrl: 'https://demo.example.com/v1',
        model: 'demo-model',
        keyPreview: 'DEMO',
        keyPresent: true,
        source: 'fallback',
      },
    },
    currentIteration: 6,
    bestMetricValue: 0.97461,
    bestIteration: 6,
    failureCount: 1,
    iterations: [
      {
        id: 'demo-iter-1',
        index: 1,
        status: 'completed',
        hypothesis: 'Warm transformed fixtures once per fold to cut duplicate preprocessing.',
        change: 'Cache transformed benchmark fixtures',
        reasoning: 'The first profile showed repeated feature transforms dominating runtime, so the candidate caches fold-local transformed fixtures.',
        metricValue: 0.96812,
        improvement: 0.004836,
        commitHash: '48d9aef05c71',
        startedAt: '2026-05-05T18:32:00.000Z',
        endedAt: '2026-05-05T18:36:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-1-report.md'],
      },
      {
        id: 'demo-iter-2',
        index: 2,
        status: 'completed',
        hypothesis: 'Memoizing parser output may help, but could add stale branch overhead.',
        change: 'Attempt aggressive memoization',
        reasoning: 'The cached parser path reduced allocations, but lookup overhead ate into the gain on small batches.',
        metricValue: 0.96741,
        improvement: -0.00071,
        commitHash: '6b8f1c02d4ab',
        startedAt: '2026-05-05T18:37:00.000Z',
        endedAt: '2026-05-05T18:41:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-2-report.md'],
      },
      {
        id: 'demo-iter-3',
        index: 3,
        status: 'completed',
        hypothesis: 'Flattening the hot parser branch should improve consistency on the benchmark path.',
        change: 'Inline hot-path parser branch',
        reasoning: 'Inlining the dominant branch removed a repeated dispatch and lifted top-line accuracy after retraining.',
        metricValue: 0.97283,
        improvement: 0.00542,
        commitHash: '8ce14b76614f',
        startedAt: '2026-05-05T18:42:00.000Z',
        endedAt: '2026-05-05T18:47:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-3-report.md'],
      },
      {
        id: 'demo-iter-4',
        index: 4,
        status: 'failed',
        hypothesis: 'Removing the validation pass may speed iteration turnover if safety checks are redundant.',
        change: 'Remove redundant validation pass',
        reasoning: 'This candidate tripped a dataset schema mismatch before evaluation completed.',
        metricValue: null,
        improvement: null,
        commitHash: '9d1f36f1b22a',
        error: 'Validation schema drift detected in fold_03 fixtures.',
        startedAt: '2026-05-05T18:48:00.000Z',
        endedAt: '2026-05-05T18:50:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-4-error.log'],
      },
      {
        id: 'demo-iter-5',
        index: 5,
        status: 'completed',
        hypothesis: 'A slightly larger batch should amortize IO without destabilizing training.',
        change: 'Tune batching threshold',
        reasoning: 'The higher threshold improved throughput but regressed final accuracy versus the best checkpoint.',
        metricValue: 0.97194,
        improvement: -0.00089,
        commitHash: 'bb20c4a9e3d1',
        startedAt: '2026-05-05T18:51:00.000Z',
        endedAt: '2026-05-05T18:55:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-5-report.md'],
      },
      {
        id: 'demo-iter-6',
        index: 6,
        status: 'completed',
        hypothesis: 'Combining cached fixtures with the inlined parser should capture both wins.',
        change: 'Fuse cached fixtures with parser fast-path',
        reasoning: 'The combined candidate preserved parser gains while removing repeated normalization work.',
        metricValue: 0.97461,
        improvement: 0.00267,
        commitHash: 'd31ab9f047ce',
        startedAt: '2026-05-05T18:56:00.000Z',
        endedAt: '2026-05-05T19:02:00.000Z',
        artifactPaths: ['./artifacts/autoresearch/demo/iter-6-report.md'],
      },
    ],
    events: [
      {
        id: 'demo-event-1',
        runId: AUTORESEARCH_DEMO_RUN_ID,
        timestamp: '2026-05-05T18:31:00.000Z',
        level: 'info',
        phase: 'preflight',
        message: 'Benchmark workspace prepared and baseline metric loaded.',
      },
      {
        id: 'demo-event-2',
        runId: AUTORESEARCH_DEMO_RUN_ID,
        timestamp: '2026-05-05T18:42:00.000Z',
        level: 'info',
        phase: 'agent_execution',
        message: 'Inlining parser branch produced the first clear breakthrough candidate.',
      },
      {
        id: 'demo-event-3',
        runId: AUTORESEARCH_DEMO_RUN_ID,
        timestamp: '2026-05-05T18:49:00.000Z',
        level: 'warn',
        phase: 'evaluation',
        message: 'Validation schema drift blocked iteration 4 before metric capture.',
      },
      {
        id: 'demo-event-4',
        runId: AUTORESEARCH_DEMO_RUN_ID,
        timestamp: '2026-05-05T19:02:00.000Z',
        level: 'info',
        phase: 'system',
        message: 'Run completed with a new best score and a stable final candidate.',
      },
    ],
    summary: 'Final candidate improved cv_accuracy from 0.963284 to 0.97461 after six iterations, with one failed experiment safely discarded.',
    liveOutputExcerpt: [
      '$ autoresearch run --metric cv_accuracy --direction higher',
      'baseline=cv_accuracy:0.963284',
      'iter#1 keep 0.96812 Cache transformed benchmark fixtures',
      'iter#2 discard 0.96741 Attempt aggressive memoization',
      'iter#3 keep 0.97283 Inline hot-path parser branch',
      'iter#4 failed Validation schema drift detected in fold_03 fixtures.',
      'iter#5 discard 0.97194 Tune batching threshold',
      'iter#6 keep 0.97461 Fuse cached fixtures with parser fast-path',
    ].join('\n'),
  };
}

export default createAutoResearchDemoRun;
