/**
 * AutoResearch Harness — Patch Gate Artifacts
 *
 * Each self-improve iteration produces a self-contained set of artifacts
 * under its iteration run dir:
 *
 *   - diff.patch       unified diff between the iteration code checkout
 *                      and the snapshot baseline (or the parent baseline
 *                      for non-snapshot runs).
 *   - result.json      the structured SelfImproveResult v2 (or v1 if
 *                      legacy).
 *   - events.jsonl     the JSONL event log for the run.
 *   - logs/verify-*.{stdout,stderr}.log
 *                      per-command verification output.
 *   - apply.md         human-readable apply/discard instructions. The
 *                      patch is NOT auto-applied to the original repo.
 *   - revert.md        how to revert a future applied patch.
 *
 * The harness writes these artifacts in `writePatchGateArtifacts`.
 * The apply / revert text is generated by the harness; the user (or
 * a future automation) must explicitly call `applyPatch` to push
 * changes back into the source repo.
 */

import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import type { SelfImproveResult } from './selfImprove/schema';
import type { SelfImproveResultV2 } from './selfImprove/schemaV2';
import { redactSecrets } from './jsonlEventLog';

export interface PatchGatePaths {
  diffPath: string;
  resultPath: string;
  eventsPath: string;
  applyInstructionsPath: string;
  revertInstructionsPath: string;
  logsDir: string;
}

export interface WritePatchGateInput {
  iterDir: string;
  diff: string;
  result: SelfImproveResult | SelfImproveResultV2;
  eventsPath: string;
  verificationLogs?: Array<{ command: string; stdout: string; stderr: string }>;
  originalRepoPath?: string;
}

export function derivePatchGatePaths(iterDir: string): PatchGatePaths {
  return {
    diffPath: path.join(iterDir, 'diff.patch'),
    resultPath: path.join(iterDir, 'result.json'),
    eventsPath: path.join(iterDir, 'events.jsonl'),
    applyInstructionsPath: path.join(iterDir, 'apply.md'),
    revertInstructionsPath: path.join(iterDir, 'revert.md'),
    logsDir: path.join(iterDir, 'logs'),
  };
}

/**
 * Write the patch gate artifacts. Always non-destructive: writes only
 * files inside `iterDir`. Does NOT touch the original repo.
 */
export async function writePatchGateArtifacts(input: WritePatchGateInput): Promise<PatchGatePaths> {
  const paths = derivePatchGatePaths(input.iterDir);
  await fs.mkdir(paths.logsDir, { recursive: true });

  await fs.writeFile(paths.diffPath, input.diff, 'utf8');
  await fs.writeFile(
    paths.resultPath,
    `${JSON.stringify(input.result, null, 2)}\n`,
    'utf8',
  );

  // Copy/link events.jsonl to the canonical name inside iterDir if needed.
  try {
    await fs.access(input.eventsPath);
    if (path.resolve(input.eventsPath) !== path.resolve(paths.eventsPath)) {
      await fs.copyFile(input.eventsPath, paths.eventsPath);
    }
  } catch {
    // events.jsonl is optional; skip silently.
  }

  // Per-command verification logs.
  for (const entry of input.verificationLogs ?? []) {
    const safe = sanitizeForLogName(entry.command);
    await fs.writeFile(path.join(paths.logsDir, `verify-${safe}.stdout.log`), entry.stdout, 'utf8');
    await fs.writeFile(path.join(paths.logsDir, `verify-${safe}.stderr.log`), entry.stderr, 'utf8');
  }

  await fs.writeFile(
    paths.applyInstructionsPath,
    buildApplyMarkdown({
      iterDir: input.iterDir,
      diff: input.diff,
      result: input.result,
      originalRepoPath: input.originalRepoPath,
    }),
    'utf8',
  );

  await fs.writeFile(
    paths.revertInstructionsPath,
    buildRevertMarkdown({ iterDir: input.iterDir, diff: input.diff }),
    'utf8',
  );

  return paths;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function sanitizeForLogName(command: string): string {
  return command
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'cmd';
}

function buildApplyMarkdown(input: {
  iterDir: string;
  diff: string;
  result: SelfImproveResult | SelfImproveResultV2;
  originalRepoPath?: string;
}): string {
  // v1 and v2 share the v1 base fields, so we can read them from a v1 view.
  const v1View = input.result as SelfImproveResult;
  const v2View = input.result as Partial<SelfImproveResultV2>;
  const lines: string[] = [];
  lines.push('# Patch Gate — Apply Instructions');
  lines.push('');
  lines.push(`- Iteration dir: \`${input.iterDir}\``);
  lines.push(`- Diff: \`${path.join(input.iterDir, 'diff.patch')}\``);
  lines.push(`- Result: \`${path.join(input.iterDir, 'result.json')}\``);
  lines.push(`- Events: \`${path.join(input.iterDir, 'events.jsonl')}\``);
  if (input.originalRepoPath) {
    lines.push(`- Original repo: \`${input.originalRepoPath}\``);
  }
  lines.push('');
  lines.push('## Status');
  lines.push(`- status: \`${v1View.status}\``);
  lines.push(`- riskLevel: \`${v1View.riskLevel}\``);
  lines.push(`- changedFiles (${v1View.changedFiles.length}): ${v1View.changedFiles.map((f) => `\`${f}\``).join(', ') || '_(none)_'}`);
  if (v2View.issue) {
    lines.push(`- issue.summary: ${v2View.issue.summary}`);
    lines.push(`- issue.category: \`${v2View.issue.category}\``);
    lines.push(`- issue.severity: \`${v2View.issue.severity}\``);
  }
  lines.push('');
  lines.push('## Default behavior');
  lines.push('The harness does **NOT** auto-apply the patch to the original repository.');
  lines.push('Review the diff and the verification logs below. Apply manually if you choose:');
  lines.push('');
  lines.push('```bash');
  if (input.originalRepoPath) {
    lines.push(`cd ${input.originalRepoPath}`);
    lines.push('git apply --check <diff.patch> && git apply <diff.patch>');
  } else {
    lines.push('# cd to your target repository first');
    lines.push('git apply --check <diff.patch> && git apply <diff.patch>');
  }
  lines.push('```');
  lines.push('');
  lines.push('## Diff preview');
  lines.push('```diff');
  lines.push(input.diff.slice(0, 4_000));
  if (input.diff.length > 4_000) lines.push('…[truncated]');
  lines.push('```');
  lines.push('');
  lines.push('## Sanitized summary');
  lines.push('```');
  lines.push(redactSecrets(String(v1View.summary)) as string);
  lines.push('```');
  return lines.join('\n');
}

function buildRevertMarkdown(input: { iterDir: string; diff: string }): string {
  const lines: string[] = [];
  lines.push('# Patch Gate — Revert Instructions');
  lines.push('');
  lines.push(`- Iteration dir: \`${input.iterDir}\``);
  lines.push('');
  lines.push('To revert a patch that was already applied, run from the target repository:');
  lines.push('');
  lines.push('```bash');
  lines.push('git apply -R <diff.patch>');
  lines.push('```');
  lines.push('');
  lines.push('If the patch is staged or committed, use `git restore` / `git revert` accordingly.');
  return lines.join('\n');
}

/**
 * Returns true if the diff is non-empty.
 */
export function diffHasChanges(diff: string): boolean {
  return /^\+\+\+\s|^---\s/m.test(diff) && /^[+-]/m.test(diff);
}

/**
 * Count added/deleted lines in a unified diff.
 */
export function countDiffLines(diff: string): { added: number; deleted: number } {
  let added = 0;
  let deleted = 0;
  for (const line of diff.split('\n')) {
    if (line.startsWith('+++') || line.startsWith('---')) continue;
    if (line.startsWith('+')) added += 1;
    else if (line.startsWith('-')) deleted += 1;
  }
  return { added, deleted };
}
